### ISSUE TITLE
Error: Received a non-Vinyl object in `dest()`

### ISSUE THREAD

**Issue by arthabus** [Mitranim/gulp-html-to-js#5]
Tried to execute a task from the readme but getting this error:

Error: Received a non-Vinyl object in `dest()`

Task:

gulp.task('views:compile', function() {
    return gulp.src('chrome/html/**/*') <- this is my htmls path
        .pipe(htmlToJs())
        .pipe(gulp.dest('dist'));
});

package.json:

  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-html-to-js": "0.0.5",
  },

Any ideas on how to overcome that are much appreciated

Thanks!

**Comment by mitranim** [comment]
Pushed an update, should be working now.

**Comment by j-dc** [comment]
Error still occurs when using concat:"filename"

```
root
|-->Folder: dist
|-->Folder:src
    |-->source1.html
    |-->source2.html
|-->gulpfile.js
|-->package.json

```
gulpfile.js:
```
var gulp = require('gulp');
var htmlToJs = require('gulp-html-to-js');
 

gulp.task('noConcat', 
    ()=>{return gulp.src(['src/**/*'])
        .pipe(htmlToJs())
        .pipe(gulp.dest('dist'))
    }
);
gulp.task('concat', 
    ()=>{return gulp.src(['src/**/*'])
        .pipe(htmlToJs({concat:"views.js"}))
        .pipe(gulp.dest('dist'))
    }
);
```
```
package.json
{
  "devDependencies": {
    "gulp": "^4.0.0",
    "gulp-html-to-js": "0.0.6"
  }
}
```

output without concat:

```
gulp noConcat
[15:54:13] Using gulpfile xxx\gulpfile.js
[15:54:13] Starting 'noConcat'...
[15:54:13] Finished 'noConcat' after 59 ms

```

output with concat:

```
gulp concat
[15:56:14] Using gulpfile xxx\gulpfile.js
[15:56:14] Starting 'concat'...
[15:56:14] 'concat' errored after 59 ms
[15:56:14] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (xxx\node_modules\vinyl-fs\lib\dest\prepare.js:16:17)
    at DestroyableTransform.Transform._read (xxx\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (xxx\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (xxx\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (xxx\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (xxx\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Pumpify.Duplexify._write (xxx\node_modules\duplexify\index.js:208:22)
    at doWrite (xxx\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer xxx\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Pumpify.Writable.write (xxx\node_modules\readable-stream\lib\_stream_writable.js:334:11)
```

**Comment by j-dc** [comment]
It does work when changing line 49in index.js
(removing this.push)

from (wrong):
```
   done(undefined, this.push(new File({
        path: options.concat,
        contents: Buffer.from(join(results, options))
      })))
```


to (correct):
```
 done(undefined, new File({
        path: options.concat,
        contents: Buffer.from(join(results, options))
      }))
```


**I have not tested this with gulp  3.x**

**Comment by j-dc** [comment]
This code is working:

```
return new Transform({
    objectMode: true,
    transform (file, _, done) {
      if (file.isBuffer()) {
        results.push(textToExport(file.contents.toString(), file.relative, options))
      }
      done()
    },
    flush (done) {
      this.push(new File({
        path: options.concat,
        contents: Buffer.from(join(results, options))
      }));
      done()
    }
  })
```

**Comment by mitranim** [comment]
Apologies for the delay. Just released an update that should fix this. It also makes `vinyl` a peer dependency to avoid stale versions in the future. Please check.

**Comment by j-dc** [comment]
Thank you!  
This works now!

**Comment by mitranim** [comment]
Good to hear.
